# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QCalendarWidget, QCheckBox,
                             QComboBox, QDateEdit, QGridLayout, QGroupBox, QHBoxLayout, QLabel,
                             QLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.itemTab = QtWidgets.QWidget()
        self.itemTab.setObjectName("itemTab")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.itemTab)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(20, 10, 271, 107))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.itemNameLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.itemNameLabel.setObjectName("itemNameLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.itemNameLabel)
        self.itemNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.itemNameLineEdit.setObjectName("itemNameLineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.itemNameLineEdit)
        self.tonPriceLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.tonPriceLabel.setObjectName("tonPriceLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tonPriceLabel)
        self.tonPriceLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.tonPriceLineEdit.setObjectName("tonPriceLineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tonPriceLineEdit)
        self.newItemSaveBtn = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.newItemSaveBtn.setObjectName("newItemSaveBtn")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.newItemSaveBtn)
        self.newItemPrice = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.newItemPrice.setFont(font)
        self.newItemPrice.setMidLineWidth(1)
        self.newItemPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.newItemPrice.setObjectName("newItemPrice")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.newItemPrice)
        self.tableView = QtWidgets.QTableView(self.itemTab)
        self.tableView.setGeometry(QtCore.QRect(40, 160, 411, 301))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.itemTab, "")
        self.routeTab = QtWidgets.QWidget()
        self.routeTab.setObjectName("routeTab")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.routeTab)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(40, 40, 261, 311))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.newRouteLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.newRouteLabel.setFont(font)
        self.newRouteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newRouteLabel.setObjectName("newRouteLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.newRouteLabel)
        self.chooseStartLocationLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.chooseStartLocationLabel.setObjectName("chooseStartLocationLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.chooseStartLocationLabel)
        self.chooseEndLocationLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.chooseEndLocationLabel.setObjectName("chooseEndLocationLabel")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.chooseEndLocationLabel)
        self.chooseEndLocationComboBox = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.chooseEndLocationComboBox.setObjectName("chooseEndLocationComboBox")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.chooseEndLocationComboBox)
        self.routePriceLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.routePriceLabel.setObjectName("routePriceLabel")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.routePriceLabel)
        self.routePriceLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.routePriceLineEdit.setObjectName("routePriceLineEdit")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.routePriceLineEdit)
        self.willChooseItemLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.willChooseItemLabel.setObjectName("willChooseItemLabel")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.willChooseItemLabel)
        self.willChooseItemCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.willChooseItemCheckBox.setObjectName("willChooseItemCheckBox")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.willChooseItemCheckBox)
        self.newRouteSaveBtn = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.newRouteSaveBtn.setObjectName("newRouteSaveBtn")
        self.formLayout_3.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.newRouteSaveBtn)
        self.chooseQuoteCustomer = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.chooseQuoteCustomer.setObjectName("chooseQuoteCustomer")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.chooseQuoteCustomer)
        self.chooseStartLocationComboBox = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.chooseStartLocationComboBox.setObjectName("chooseStartLocationComboBox")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.chooseStartLocationComboBox)
        self.chooseQuoteCustomerCombo = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.chooseQuoteCustomerCombo.setObjectName("chooseQuoteCustomerCombo")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.chooseQuoteCustomerCombo)
        self.tabWidget.addTab(self.routeTab, "")
        self.customerTab = QtWidgets.QWidget()
        self.customerTab.setObjectName("customerTab")
        self.formLayoutWidget = QtWidgets.QWidget(self.customerTab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 231, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.customerNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.customerNameLabel.setObjectName("customerNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.customerNameLabel)
        self.customerNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.customerNameLineEdit.setObjectName("customerNameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.customerNameLineEdit)
        self.btnSave = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnSave.setObjectName("btnSave")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnSave)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.customerTab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(280, 10, 261, 509))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.customerComboBox = QComboBox(self.formLayoutWidget_2)
        self.customerComboBox.setObjectName("customerComboBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.customerComboBox)
        self.newLocationLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.newLocationLabel.setObjectName("newLocationLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.newLocationLabel)
        self.newLocationLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.newLocationLineEdit.setObjectName("newLocationLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.newLocationLineEdit)
        self.cusLocWidget = QtWidgets.QListWidget(self.formLayoutWidget_2)
        self.cusLocWidget.setObjectName("cusLocWidget")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.cusLocWidget)
        self.btnSaveLocation = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btnSaveLocation.setObjectName("btnSaveLocation")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.btnSaveLocation)
        self.btnRefreshLocations = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btnRefreshLocations.setObjectName("btnRefreshLocations")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btnRefreshLocations)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.tabWidget.addTab(self.customerTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.itemDiscountsTable = QtWidgets.QTableView(self.tab)
        self.itemDiscountsTable.setGeometry(QtCore.QRect(50, 40, 701, 421))
        self.itemDiscountsTable.setObjectName("itemDiscountsTable")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuShow_Tables = QtWidgets.QMenu(self.menubar)
        self.menuShow_Tables.setObjectName("menuShow_Tables")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Route = QtWidgets.QAction(MainWindow)
        self.actionNew_Route.setObjectName("actionNew_Route")
        self.actionNew_Item = QtWidgets.QAction(MainWindow)
        self.actionNew_Item.setObjectName("actionNew_Item")
        self.actionNew_Customer = QtWidgets.QAction(MainWindow)
        self.actionNew_Customer.setObjectName("actionNew_Customer")
        self.actionNew_Location = QtWidgets.QAction(MainWindow)
        self.actionNew_Location.setObjectName("actionNew_Location")
        self.actionItem_Customer = QtWidgets.QAction(MainWindow)
        self.actionItem_Customer.setObjectName("actionItem_Customer")
        self.menuFile.addAction(self.actionNew_Route)
        self.menuFile.addAction(self.actionNew_Item)
        self.menuFile.addAction(self.actionNew_Customer)
        self.menuFile.addAction(self.actionNew_Location)
        self.menuShow_Tables.addAction(self.actionItem_Customer)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuShow_Tables.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.itemNameLabel.setText(_translate("MainWindow", "Item Name"))
        self.tonPriceLabel.setText(_translate("MainWindow", "Ton Price"))
        self.newItemSaveBtn.setText(_translate("MainWindow", "Save"))
        self.newItemPrice.setText(_translate("MainWindow", "New Item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.itemTab), _translate("MainWindow", "Item Page"))
        self.newRouteLabel.setText(_translate("MainWindow", "Define New Quote"))
        self.chooseStartLocationLabel.setText(_translate("MainWindow", "Choose Start Location"))
        self.chooseEndLocationLabel.setText(_translate("MainWindow", "Choose End Location"))
        self.routePriceLabel.setText(_translate("MainWindow", "Route Price"))
        self.willChooseItemLabel.setText(_translate("MainWindow", "Will choose Item?"))
        self.newRouteSaveBtn.setText(_translate("MainWindow", "Save"))
        self.chooseQuoteCustomer.setText(_translate("MainWindow", "Choose Customer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.routeTab), _translate("MainWindow", "Route Page"))
        self.customerTab.setToolTip(_translate("MainWindow", "<html><head/><body><p>customer Tab</p></body></html>"))
        self.customerTab.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Customer Tab</p></body></html>"))
        self.label.setText(_translate("MainWindow", "New Customer"))
        self.customerNameLabel.setText(_translate("MainWindow", "Customer Name"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.newLocationLabel.setText(_translate("MainWindow", "New Location"))
        self.btnSaveLocation.setText(_translate("MainWindow", "Save"))
        self.btnRefreshLocations.setText(_translate("MainWindow", "Refresh"))
        self.label_2.setText(_translate("MainWindow", "Customer List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.customerTab), _translate("MainWindow", "Customer Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Discounts Page"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuShow_Tables.setTitle(_translate("MainWindow", "Show Tables"))
        self.actionNew_Route.setText(_translate("MainWindow", "New Route"))
        self.actionNew_Item.setText(_translate("MainWindow", "New Item"))
        self.actionNew_Customer.setText(_translate("MainWindow", "New Customer"))
        self.actionNew_Location.setText(_translate("MainWindow", "New Location"))
        self.actionItem_Customer.setText(_translate("MainWindow", "Item Price / Customer"))

