# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 611))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.itemTab = QtGui.QWidget()
        self.itemTab.setObjectName(_fromUtf8("itemTab"))
        self.formLayoutWidget_4 = QtGui.QWidget(self.itemTab)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(20, 10, 271, 107))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.itemNameLabel = QtGui.QLabel(self.formLayoutWidget_4)
        self.itemNameLabel.setObjectName(_fromUtf8("itemNameLabel"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.itemNameLabel)
        self.itemNameLineEdit = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.itemNameLineEdit.setObjectName(_fromUtf8("itemNameLineEdit"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.itemNameLineEdit)
        self.tonPriceLabel = QtGui.QLabel(self.formLayoutWidget_4)
        self.tonPriceLabel.setObjectName(_fromUtf8("tonPriceLabel"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.tonPriceLabel)
        self.tonPriceLineEdit = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.tonPriceLineEdit.setObjectName(_fromUtf8("tonPriceLineEdit"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.tonPriceLineEdit)
        self.newItemSaveBtn = QtGui.QPushButton(self.formLayoutWidget_4)
        self.newItemSaveBtn.setObjectName(_fromUtf8("newItemSaveBtn"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.newItemSaveBtn)
        self.newItemPrice = QtGui.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.newItemPrice.setFont(font)
        self.newItemPrice.setMidLineWidth(1)
        self.newItemPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.newItemPrice.setObjectName(_fromUtf8("newItemPrice"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.SpanningRole, self.newItemPrice)
        self.tableView = QtGui.QTableView(self.itemTab)
        self.tableView.setGeometry(QtCore.QRect(40, 160, 411, 301))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tabWidget.addTab(self.itemTab, _fromUtf8(""))
        self.routeTab = QtGui.QWidget()
        self.routeTab.setObjectName(_fromUtf8("routeTab"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.routeTab)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(40, 40, 261, 311))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.chooseStartLocationLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.chooseStartLocationLabel.setObjectName(_fromUtf8("chooseStartLocationLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.chooseStartLocationLabel)
        self.chooseStartLocationComboBox = QtGui.QComboBox(self.formLayoutWidget_3)
        self.chooseStartLocationComboBox.setObjectName(_fromUtf8("chooseStartLocationComboBox"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.SpanningRole, self.chooseStartLocationComboBox)
        self.chooseEndLocationLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.chooseEndLocationLabel.setObjectName(_fromUtf8("chooseEndLocationLabel"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.chooseEndLocationLabel)
        self.chooseEndLocationComboBox = QtGui.QComboBox(self.formLayoutWidget_3)
        self.chooseEndLocationComboBox.setObjectName(_fromUtf8("chooseEndLocationComboBox"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.SpanningRole, self.chooseEndLocationComboBox)
        self.routePriceLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.routePriceLabel.setObjectName(_fromUtf8("routePriceLabel"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.routePriceLabel)
        self.routePriceLineEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.routePriceLineEdit.setObjectName(_fromUtf8("routePriceLineEdit"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.SpanningRole, self.routePriceLineEdit)
        self.willChooseItemLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.willChooseItemLabel.setObjectName(_fromUtf8("willChooseItemLabel"))
        self.formLayout_3.setWidget(14, QtGui.QFormLayout.LabelRole, self.willChooseItemLabel)
        self.willChooseItemCheckBox = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.willChooseItemCheckBox.setObjectName(_fromUtf8("willChooseItemCheckBox"))
        self.formLayout_3.setWidget(14, QtGui.QFormLayout.FieldRole, self.willChooseItemCheckBox)
        self.newRouteSaveBtn = QtGui.QPushButton(self.formLayoutWidget_3)
        self.newRouteSaveBtn.setObjectName(_fromUtf8("newRouteSaveBtn"))
        self.formLayout_3.setWidget(15, QtGui.QFormLayout.FieldRole, self.newRouteSaveBtn)
        self.newRouteLabel = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.newRouteLabel.setFont(font)
        self.newRouteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newRouteLabel.setObjectName(_fromUtf8("newRouteLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.SpanningRole, self.newRouteLabel)
        self.tabWidget.addTab(self.routeTab, _fromUtf8(""))
        self.customerTab = QtGui.QWidget()
        self.customerTab.setObjectName(_fromUtf8("customerTab"))
        self.formLayoutWidget = QtGui.QWidget(self.customerTab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 231, 121))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label)
        self.customerNameLabel = QtGui.QLabel(self.formLayoutWidget)
        self.customerNameLabel.setObjectName(_fromUtf8("customerNameLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.customerNameLabel)
        self.customerNameLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.customerNameLineEdit.setObjectName(_fromUtf8("customerNameLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.customerNameLineEdit)
        self.btnSave = QtGui.QPushButton(self.formLayoutWidget)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.btnSave)
        self.formLayoutWidget_2 = QtGui.QWidget(self.customerTab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(280, 10, 261, 509))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.customerComboBox = QtGui.QComboBox(self.formLayoutWidget_2)
        self.customerComboBox.setObjectName(_fromUtf8("customerComboBox"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.SpanningRole, self.customerComboBox)
        self.newLocationLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.newLocationLabel.setObjectName(_fromUtf8("newLocationLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.newLocationLabel)
        self.newLocationLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.newLocationLineEdit.setObjectName(_fromUtf8("newLocationLineEdit"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.SpanningRole, self.newLocationLineEdit)
        self.cusLocWidget = QtGui.QListWidget(self.formLayoutWidget_2)
        self.cusLocWidget.setObjectName(_fromUtf8("cusLocWidget"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.SpanningRole, self.cusLocWidget)
        self.btnSaveLocation = QtGui.QPushButton(self.formLayoutWidget_2)
        self.btnSaveLocation.setObjectName(_fromUtf8("btnSaveLocation"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.btnSaveLocation)
        self.btnRefreshLocations = QtGui.QPushButton(self.formLayoutWidget_2)
        self.btnRefreshLocations.setObjectName(_fromUtf8("btnRefreshLocations"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.btnRefreshLocations)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_2)
        self.tabWidget.addTab(self.customerTab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuShow_Tables = QtGui.QMenu(self.menubar)
        self.menuShow_Tables.setObjectName(_fromUtf8("menuShow_Tables"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Route = QtGui.QAction(MainWindow)
        self.actionNew_Route.setObjectName(_fromUtf8("actionNew_Route"))
        self.actionNew_Item = QtGui.QAction(MainWindow)
        self.actionNew_Item.setObjectName(_fromUtf8("actionNew_Item"))
        self.actionNew_Customer = QtGui.QAction(MainWindow)
        self.actionNew_Customer.setObjectName(_fromUtf8("actionNew_Customer"))
        self.actionNew_Location = QtGui.QAction(MainWindow)
        self.actionNew_Location.setObjectName(_fromUtf8("actionNew_Location"))
        self.actionItem_Customer = QtGui.QAction(MainWindow)
        self.actionItem_Customer.setObjectName(_fromUtf8("actionItem_Customer"))
        self.menuFile.addAction(self.actionNew_Route)
        self.menuFile.addAction(self.actionNew_Item)
        self.menuFile.addAction(self.actionNew_Customer)
        self.menuFile.addAction(self.actionNew_Location)
        self.menuShow_Tables.addAction(self.actionItem_Customer)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuShow_Tables.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.itemNameLabel.setText(_translate("MainWindow", "Item Name", None))
        self.tonPriceLabel.setText(_translate("MainWindow", "Ton Price", None))
        self.newItemSaveBtn.setText(_translate("MainWindow", "Save", None))
        self.newItemPrice.setText(_translate("MainWindow", "New Item", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.itemTab), _translate("MainWindow", "Item Page", None))
        self.chooseStartLocationLabel.setText(_translate("MainWindow", "Choose Start Location", None))
        self.chooseEndLocationLabel.setText(_translate("MainWindow", "Choose End Location", None))
        self.routePriceLabel.setText(_translate("MainWindow", "Route Price", None))
        self.willChooseItemLabel.setText(_translate("MainWindow", "Will choose Item?", None))
        self.newRouteSaveBtn.setText(_translate("MainWindow", "Save", None))
        self.newRouteLabel.setText(_translate("MainWindow", "New Route", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.routeTab), _translate("MainWindow", "Route Page", None))
        self.customerTab.setToolTip(_translate("MainWindow", "<html><head/><body><p>customer Tab</p></body></html>", None))
        self.customerTab.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Customer Tab</p></body></html>", None))
        self.label.setText(_translate("MainWindow", "New Customer", None))
        self.customerNameLabel.setText(_translate("MainWindow", "Customer Name", None))
        self.btnSave.setText(_translate("MainWindow", "Save", None))
        self.newLocationLabel.setText(_translate("MainWindow", "New Location", None))
        self.btnSaveLocation.setText(_translate("MainWindow", "Save", None))
        self.btnRefreshLocations.setText(_translate("MainWindow", "Refresh", None))
        self.label_2.setText(_translate("MainWindow", "Customer List", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.customerTab), _translate("MainWindow", "Customer Page", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuShow_Tables.setTitle(_translate("MainWindow", "Show Tables", None))
        self.actionNew_Route.setText(_translate("MainWindow", "New Route", None))
        self.actionNew_Item.setText(_translate("MainWindow", "New Item", None))
        self.actionNew_Customer.setText(_translate("MainWindow", "New Customer", None))
        self.actionNew_Location.setText(_translate("MainWindow", "New Location", None))
        self.actionItem_Customer.setText(_translate("MainWindow", "Item Price / Customer", None))

